# Generated by Django 4.0.2 on 2022-02-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biograohy',
            new_name='biography',
        ),
    ]
