# Generated by Django 4.0.2 on 2022-02-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
